name: Publicar NuGet
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Publicar Pacote NuGet
        uses: brandedoutcast/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: Fmd.Net.Core/Fmd.Net.Core.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
